# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BasicInfoDialogue.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(527, 342)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblName = QtWidgets.QLabel(self.centralwidget)
        self.lblName.setGeometry(QtCore.QRect(20, 10, 47, 13))
        self.lblName.setObjectName("lblName")
        self.lblCNIC = QtWidgets.QLabel(self.centralwidget)
        self.lblCNIC.setGeometry(QtCore.QRect(270, 10, 47, 13))
        self.lblCNIC.setObjectName("lblCNIC")
        self.txtbxName = QtWidgets.QTextEdit(self.centralwidget)
        self.txtbxName.setGeometry(QtCore.QRect(20, 30, 231, 21))
        self.txtbxName.setObjectName("txtbxName")
        self.txtbxCNIC = QtWidgets.QTextEdit(self.centralwidget)
        self.txtbxCNIC.setGeometry(QtCore.QRect(270, 30, 231, 21))
        self.txtbxCNIC.setObjectName("txtbxCNIC")
        self.cmbxRelation = QtWidgets.QComboBox(self.centralwidget)
        self.cmbxRelation.setGeometry(QtCore.QRect(20, 80, 231, 22))
        self.cmbxRelation.setObjectName("cmbxRelation")
        self.lblRelationcmbx = QtWidgets.QLabel(self.centralwidget)
        self.lblRelationcmbx.setGeometry(QtCore.QRect(20, 60, 47, 13))
        self.lblRelationcmbx.setObjectName("lblRelationcmbx")
        self.txtbxRelation = QtWidgets.QTextEdit(self.centralwidget)
        self.txtbxRelation.setGeometry(QtCore.QRect(270, 80, 231, 21))
        self.txtbxRelation.setObjectName("txtbxRelation")
        self.lblRelation = QtWidgets.QLabel(self.centralwidget)
        self.lblRelation.setGeometry(QtCore.QRect(270, 60, 47, 13))
        self.lblRelation.setObjectName("lblRelation")
        self.txtbxEmail = QtWidgets.QTextEdit(self.centralwidget)
        self.txtbxEmail.setGeometry(QtCore.QRect(270, 130, 231, 21))
        self.txtbxEmail.setObjectName("txtbxEmail")
        self.lblContactNo = QtWidgets.QLabel(self.centralwidget)
        self.lblContactNo.setGeometry(QtCore.QRect(20, 110, 81, 16))
        self.lblContactNo.setObjectName("lblContactNo")
        self.lblEmail = QtWidgets.QLabel(self.centralwidget)
        self.lblEmail.setGeometry(QtCore.QRect(270, 110, 47, 13))
        self.lblEmail.setObjectName("lblEmail")
        self.txtbxContactNo = QtWidgets.QTextEdit(self.centralwidget)
        self.txtbxContactNo.setGeometry(QtCore.QRect(20, 130, 231, 21))
        self.txtbxContactNo.setObjectName("txtbxContactNo")
        self.txtbxAddress = QtWidgets.QTextEdit(self.centralwidget)
        self.txtbxAddress.setGeometry(QtCore.QRect(20, 180, 231, 51))
        self.txtbxAddress.setObjectName("txtbxAddress")
        self.lblAdress = QtWidgets.QLabel(self.centralwidget)
        self.lblAdress.setGeometry(QtCore.QRect(20, 160, 47, 13))
        self.lblAdress.setObjectName("lblAdress")
        self.ckbxUseSecondForm = QtWidgets.QCheckBox(self.centralwidget)
        self.ckbxUseSecondForm.setGeometry(QtCore.QRect(270, 170, 241, 31))
        self.ckbxUseSecondForm.setObjectName("ckbxUseSecondForm")
        self.ckbxPowerAttornet = QtWidgets.QCheckBox(self.centralwidget)
        self.ckbxPowerAttornet.setGeometry(QtCore.QRect(270, 200, 211, 31))
        self.ckbxPowerAttornet.setObjectName("ckbxPowerAttornet")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(430, 240, 75, 31))
        self.btnAdd.setObjectName("btnAdd")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(350, 240, 75, 31))
        self.btnCancel.setObjectName("btnCancel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 527, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblName.setText(_translate("MainWindow", "Name"))
        self.lblCNIC.setText(_translate("MainWindow", "CNIC"))
        self.lblRelationcmbx.setText(_translate("MainWindow", "Relation"))
        self.lblRelation.setText(_translate("MainWindow", "Relation"))
        self.lblContactNo.setText(_translate("MainWindow", "ContactNo"))
        self.lblEmail.setText(_translate("MainWindow", "Email"))
        self.lblAdress.setText(_translate("MainWindow", "Address"))
        self.ckbxUseSecondForm.setText(_translate("MainWindow", "Use this Second Party in the form"))
        self.ckbxPowerAttornet.setText(_translate("MainWindow", "Through Power Of Attorney"))
        self.btnAdd.setText(_translate("MainWindow", "Add"))
        self.btnCancel.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
